index:
    path: /
    controller: App\Controller\Home::handle

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

organisation:
    resource: routes/organisations.yaml
    prefix: organisations

speaker:
    resource: routes/speakers.yaml
    prefix: speakers

sponsorship_level:
    resource: routes/sponsorshipLevel.yaml
    prefix: sponsorship-level

sponsorship_benefit:
    resource: routes/sponsorshipBenefit.yaml
    prefix: sponsorship-benefit

sponsorship_level_benefit:
    resource: routes/sponsorshipLevelBenefit.yaml
    prefix: sponsorship-level-benefit

special_benefit:
    resource: routes/specialBenefit.yaml
    prefix: special-benefit

talks:
    resource: routes/talks.yaml
    prefix: talks
